import Link from "next/link";
import { AppShell } from "@/components/ui/app-shell";
import { PrototypeBadge } from "@/components/ui/prototype-badge";
import { demoParticipant, demoReport, resultRows } from "@/lib/ist-data";

export default async function HrReportPage({ params }: { params: Promise<{ sessionId: string }> }) {
  const { sessionId } = await params;
  const isFinal = demoReport.resultStatus === "final";

  return (
    <AppShell
      eyebrow="Report Preview"
      title={`Laporan sesi ${sessionId}`}
      description="Laporan hanya dapat diunduh setelah hasil berstatus final. Setiap file final menyimpan hash dan versi untuk audit."
    >
      <section className="grid gap-6 xl:grid-cols-[0.9fr_1.1fr]">
        <article className="rounded-2xl border border-[var(--border-default)] bg-[var(--surface-panel)] p-6 shadow-[var(--shadow-subtle)]">
          <div className="flex flex-wrap gap-3">
            <PrototypeBadge tone={isFinal ? "success" : "warning"}>
              Result: {demoReport.resultStatus}
            </PrototypeBadge>
            <PrototypeBadge>Bukan laporan resmi</PrototypeBadge>
          </div>

          <dl className="mt-6 grid gap-4 text-sm">
            {[
              ["Report ID", demoReport.id],
              ["Versi laporan", demoReport.reportVersion],
              ["File hash", demoReport.fileHash],
              ["Generated by", demoReport.generatedBy],
              ["Form version", demoReport.formVersion],
              ["Norm version", demoReport.normVersion],
              ["Engine version", demoReport.engineVersion],
            ].map(([label, value]) => (
              <div
                key={label}
                className="flex items-baseline justify-between gap-4 border-b border-[var(--border-subtle)] pb-3"
              >
                <dt className="text-[var(--text-muted)]">{label}</dt>
                <dd className="font-mono text-[var(--text-primary)]">{value}</dd>
              </div>
            ))}
          </dl>

          <div className="mt-6 flex flex-wrap gap-3">
            <button
              type="button"
              disabled={!isFinal}
              className="inline-flex h-12 items-center justify-center rounded-xl bg-[var(--accent-primary)] px-5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50"
            >
              Unduh PDF final
            </button>
            <Link
              href={`/hr/results/${sessionId}`}
              className="inline-flex h-12 items-center justify-center rounded-xl border border-[var(--border-default)] px-5 text-sm font-semibold text-[var(--text-primary)] hover:bg-[var(--surface-subtle)]"
            >
              Kembali ke hasil
            </Link>
          </div>
          {!isFinal ? (
            <p className="mt-4 text-sm leading-6 text-[var(--text-secondary)]">
              Tombol unduh terkunci karena hasil belum difinalisasi. Finalisasi dilakukan dari
              halaman hasil setelah review selesai.
            </p>
          ) : null}
        </article>

        <article className="rounded-2xl border border-[var(--border-default)] bg-[var(--surface-base)] p-6">
          <p className="text-sm font-semibold uppercase tracking-[0.08em] text-[var(--text-muted)]">
            Preview isi laporan
          </p>
          <div className="mt-5 rounded-2xl border border-[var(--border-default)] bg-[var(--surface-panel)] p-6 shadow-[var(--shadow-subtle)]">
            <p className="text-xs font-bold uppercase tracking-[0.12em] text-[var(--accent-primary)]">
              Intelligenz Struktur Test · Prototype
            </p>
            <h2 className="mt-3 text-2xl font-bold tracking-[-0.03em] text-[var(--text-primary)]">
              {demoParticipant.name}
            </h2>
            <p className="mt-1 text-sm text-[var(--text-secondary)]">
              {demoParticipant.purpose} · Tes {demoParticipant.testDate} · Sesi {sessionId}
            </p>
            <div className="mt-5 grid gap-2 text-sm text-[var(--text-primary)]">
              {resultRows.map((row) => (
                <div
                  key={row.code}
                  className="flex items-center justify-between border-b border-[var(--border-subtle)] pb-2"
                >
                  <span className="font-semibold">{row.code}</span>
                  <span>
                    RW {row.rw} · SW {row.sw} · {row.category}
                  </span>
                </div>
              ))}
            </div>
            <p className="mt-5 text-sm leading-6 text-[var(--text-secondary)]">
              IQ demo 108 (High average) · Dominance verbal-analytical. Data fiktif; tidak digunakan
              untuk keputusan rekrutmen.
            </p>
          </div>
        </article>
      </section>
    </AppShell>
  );
}
